import type { Delivery, Incident, Monitor } from './dashboard-types';

export const monitors: Monitor[] = [
  {
    id: 'api',
    name: 'Core API',
    url: 'https://api.statpulse.dev/health',
    region: 'Warsaw',
    method: 'GET',
    status: 'UP',
    uptime: 99.98,
    latency: 126,
    expectedStatus: 200,
    checks: [138, 122, 118, 128, 116, 132, 121, 119, 126, 124, 120, 126],
    incidents: 0,
    lastChecked: '18s ago',
  },
  {
    id: 'checkout',
    name: 'Checkout',
    url: 'https://store.statpulse.dev/checkout',
    region: 'Frankfurt',
    method: 'HEAD',
    status: 'DEGRADED',
    uptime: 99.42,
    latency: 482,
    expectedStatus: 200,
    checks: [238, 248, 261, 302, 355, 392, 431, 512, 498, 482, 466, 452],
    incidents: 1,
    lastChecked: '27s ago',
  },
  {
    id: 'docs',
    name: 'Docs Portal',
    url: 'https://docs.statpulse.dev',
    region: 'London',
    method: 'GET',
    status: 'UP',
    uptime: 100,
    latency: 88,
    expectedStatus: 200,
    checks: [92, 90, 87, 86, 91, 88, 84, 89, 87, 86, 90, 88],
    incidents: 0,
    lastChecked: '41s ago',
  },
  {
    id: 'webhook',
    name: 'Webhook Relay',
    url: 'https://hooks.statpulse.dev/events',
    region: 'Amsterdam',
    method: 'HEAD',
    status: 'DOWN',
    uptime: 97.18,
    latency: 0,
    expectedStatus: 204,
    checks: [181, 188, 172, 196, 214, 0, 0, 0, 0, 0, 0, 0],
    incidents: 2,
    lastChecked: '9s ago',
  },
];

export const incidents: Incident[] = [
  {
    id: 'inc-103',
    monitor: 'Webhook Relay',
    title: 'Connection timeout after redirect safety check',
    status: 'open',
    startedAt: '12:48',
    duration: '23m',
  },
  {
    id: 'inc-102',
    monitor: 'Checkout',
    title: 'Latency above 450 ms for 4 checks',
    status: 'open',
    startedAt: '12:31',
    duration: '40m',
  },
  {
    id: 'inc-101',
    monitor: 'Core API',
    title: 'Recovered after short DNS lookup failure',
    status: 'resolved',
    startedAt: '09:18',
    duration: '3m',
  },
];

export const deliveries: Delivery[] = [
  { id: 'del-1', channel: 'Telegram On-call', event: 'Incident opened', status: 'sent', time: '1m ago' },
  { id: 'del-2', channel: 'Email Ops', event: 'Cooldown active', status: 'skipped', time: '8m ago' },
  { id: 'del-3', channel: 'Telegram On-call', event: 'Incident resolved', status: 'sent', time: '2h ago' },
  { id: 'del-4', channel: 'Email Ops', event: 'Provider unavailable', status: 'failed', time: '5h ago' },
];
